sudo: required
language: node_js
node_js:
- '7'
os:
- linux
- osx
dist: xenial
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
install:
- git config --global user.name "kanna12"
- git config --global user.email "kgoku98@gmail.com"
- npm install
- npm install -g electron electron-packager electron-builder
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386; wget
  -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -; sudo apt-add-repository
  'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'; sudo apt-get update;
  sudo apt-get install --install-recommends winehq-stable; wine --version; fi
script:
- npm run dist
- pwd
- mkdir builds
- fname=$(date +%y%m%d); mkdir builds/$fname;
- ls -ltr .
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pwd ; ls -ltr .; zip -r mac-archive.zip
  ./dist; mv mac-archive.zip builds/$fname; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r archive.zip ./dist; mv archive.zip
  builds/$fname; rm -rf dist; npm run pack-win ; pwd ; ls -ltr .; zip -r win-archive.zip
  ./dist; mv win-archive.zip builds/$fname; fi
deploy:
  provider: s3
  access_key_id: AKIAQ5N4EWDLALQ44Z4B
  secret_access_key:
    secure: azWex1QqpSwMT/7P5YiUExHwjSdszMkDf9cY9AB1X21PDuBYMErHWPu0T9BlRexA6Eut/9PSmhBw0nGCvuTaqhQNcCy1DyR3LjONIi9fc8djaRpExKWguKTjl76cT0J8CK7pnv/jpj2RepKrTVcn1jMXQEXYVpZ+/JTMO60JKeFIzaHMiwONa9KOvdYzSDJLdCoEnIVI6ZEAijxHeDGZjlMPVEXTXZa+LA1sphvlT8LeDGpZNuEvw9ec/TDkO0jNvNCri42QJkFoN9JFXEOfc2pomaxnNFhRq7t4+Z7JQnVcVVnZJqWPBbEGAF9/+91gl5rLm77S1mP+i2BOeMC5CzD5oKoPs0fh7x0aSDaBGGziO2XcxEgnp6zRuKhvYrxVlWyg5tvlNgnFNp8Dqe8/+Z5+OWifYI/zc13MaaNGURx654xer7hV2nIsSUjYkcvmIqqZ6lOm6T0dnAn74uRwEvvf2oXw1C/APXi13jesJ8HO6ics+yLOazYuRShbB8fWFVD1fYqVjuUgL33MmKmS+sR+pd1Zo3RyDS8cHbeKBiHlWyO06CdaXIhwy/KPXW4Mst02Mw0vxdtF39YgJq7KaXv8ZOhgjsjoF8HJbtilwx4ajwj3H5PCK8FG2VelhzVZhKBN1qF0v4SEGS/GLNhsd2TJ84jeOVF36222caXJeSE=
  bucket: electron-deployment
  skip_cleanup: true
  on:
    repo: Kanna12/Mac-win-lix
